"""Add feedback_llm_general to Evaluacion and ResultadoCriterioLLM table

Revision ID: 0041ad0aa9f9
Revises: a8c227713250
Create Date: 2025-06-05 13:02:52.370665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041ad0aa9f9'
down_revision = 'a8c227713250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_llm_general', sa.Text(), nullable=True, comment='Feedback cualitativo general del LLM'))

    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'])

    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.drop_column('feedback_llm_general')

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'])

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    # ### end Alembic commands ###
