"""Add configuracion_formato_json to Pregunta model

Revision ID: 08512cbfa604
Revises: 4bc73f2edb10
Create Date: 2025-04-30 13:13:47.360119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08512cbfa604'
down_revision = '4bc73f2edb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'])

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'])

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    # ### end Alembic commands ###
