"""Add codigo to Usuario model

Revision ID: 1898d3f0cbda
Revises: 3d7a1795008f
Create Date: 2025-06-26 15:07:15.927974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1898d3f0cbda'
down_revision = '3d7a1795008f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuario_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_codigo'))
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
