"""Add rubrica_evaluacion to Pregunta model

Revision ID: 4fbc1e52bf52
Revises: f92b78160074
Create Date: 2025-04-28 18:27:43.268163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbc1e52bf52'
down_revision = 'f92b78160074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubrica_evaluacion', sa.Text(), nullable=True, comment='Rubrica en formato JSON para la evaluación con LLM'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.drop_column('rubrica_evaluacion')

    # ### end Alembic commands ###
