"""Initial migration

Revision ID: 5196dee07f4d
Revises: 
Create Date: 2025-04-21 21:37:18.728104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5196dee07f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo_academico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.create_index('ix_curso_codigo', ['codigo'], unique=False)

    op.create_table('regla_formato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_email', ['email'], unique=False)

    op.create_table('herramienta_analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lenguaje', sa.String(length=50), nullable=False),
    sa.Column('tipo_analisis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_analisis_id'], ['tipo_analisis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('oferta_de_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_academico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_academico_id'], ['ciclo_academico.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oferta_de_curso', schema=None) as batch_op:
        batch_op.create_index('ix_oferta_de_curso_ciclo_academico', ['ciclo_academico_id'], unique=False)

    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_de_curso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['oferta_de_curso_id'], ['oferta_de_curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.create_index('ix_examen_titulo', ['titulo'], unique=False)

    op.create_table('usuario_horario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'horario_id'),
    info={'bind_key': None}
    )
    op.create_table('configuracion_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('habilitar_formato', sa.Boolean(), nullable=True),
    sa.Column('habilitar_metricas', sa.Boolean(), nullable=True),
    sa.Column('habilitar_similitud', sa.Boolean(), nullable=True),
    sa.Column('habilitar_rendimiento', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen_herramienta',
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examen.id'], ),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramienta_analisis.id'], ),
    sa.PrimaryKeyConstraint('examen_id', 'herramienta_id'),
    info={'bind_key': None}
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('puntaje_total', sa.Float(), nullable=False),
    sa.Column('lenguaje_programacion', sa.String(length=50), nullable=False),
    sa.Column('solucion_modelo', sa.Text(), nullable=True),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_examen',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('fecha_realizado', sa.DateTime(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examen.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'examen_id')
    )
    with op.batch_alter_table('usuario_examen', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_examen_examen', ['examen_id'], unique=False)
        batch_op.create_index('ix_usuario_examen_usuario', ['usuario_id'], unique=False)

    op.create_table('caso_de_prueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('argumentos', sa.Text(), nullable=False),
    sa.Column('entrada', sa.Text(), nullable=False),
    sa.Column('salida_esperada', sa.Text(), nullable=False),
    sa.Column('puntos', sa.Float(), nullable=False),
    sa.Column('es_oculto', sa.Boolean(), nullable=True),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.Column('codigo_fuente', sa.Text(), nullable=False),
    sa.Column('archivo', sa.String(length=120), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis_formato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.ForeignKeyConstraint(['regla_id'], ['regla_formato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis_metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('metrica', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=False),
    sa.Column('informe', sa.Text(), nullable=False),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramienta_analisis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis_similitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id_1', sa.Integer(), nullable=False),
    sa.Column('entrega_id_2', sa.Integer(), nullable=False),
    sa.Column('porcentaje_similitud', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id_1'], ['entrega.id'], ),
    sa.ForeignKeyConstraint(['entrega_id_2'], ['entrega.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntaje_obtenido', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultado_de_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paso', sa.Boolean(), nullable=False),
    sa.Column('salida_obtenida', sa.Text(), nullable=False),
    sa.Column('puntos_obtenidos', sa.Float(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('caso_de_prueba_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_de_prueba_id'], ['caso_de_prueba.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_de_evaluacion')
    op.drop_table('evaluacion')
    op.drop_table('analisis_similitud')
    op.drop_table('analisis_resultado')
    op.drop_table('analisis_metrica')
    op.drop_table('analisis_formato')
    op.drop_table('entrega')
    op.drop_table('caso_de_prueba')
    with op.batch_alter_table('usuario_examen', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_examen_usuario')
        batch_op.drop_index('ix_usuario_examen_examen')

    op.drop_table('usuario_examen')
    op.drop_table('pregunta')
    op.drop_table('examen_herramienta')
    op.drop_table('configuracion_examen')
    op.drop_table('usuario_horario')
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.drop_index('ix_examen_titulo')

    op.drop_table('examen')
    op.drop_table('horario')
    with op.batch_alter_table('oferta_de_curso', schema=None) as batch_op:
        batch_op.drop_index('ix_oferta_de_curso_ciclo_academico')

    op.drop_table('oferta_de_curso')
    op.drop_table('herramienta_analisis')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_email')

    op.drop_table('usuario')
    op.drop_table('tipo_analisis')
    op.drop_table('regla_formato')
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_index('ix_curso_codigo')

    op.drop_table('curso')
    op.drop_table('ciclo_academico')
    # ### end Alembic commands ###
