"""Permitir entrada y salida_esperada nulos en CasoDePrueba

Revision ID: 8a3db9111a93
Revises: 5196dee07f4d
Create Date: 2025-04-23 19:50:53.950656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3db9111a93'
down_revision = '5196dee07f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso_de_prueba', schema=None) as batch_op:
        batch_op.alter_column('entrada',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('salida_esperada',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso_de_prueba', schema=None) as batch_op:
        batch_op.alter_column('salida_esperada',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('entrada',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
