"""Add configuracion_formato_json to Pregunta model

Revision ID: a8c227713250
Revises: 08512cbfa604
Create Date: 2025-04-30 13:22:38.206724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c227713250'
down_revision = '08512cbfa604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - ADAPTED ###
    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
        # batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE') # COMENTADO/ELIMINADO
        print("Batch alter analisis_metrica (handling FK implicitly)") # Mensaje opcional

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
         # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
         # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
         # batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'], ondelete='SET NULL') # COMENTADO/ELIMINADO
         # batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'], ondelete='CASCADE') # COMENTADO/ELIMINADO
         # Si detectó el cambio a nullable=True para herramienta_id, esa línea SÍ debe quedar:
         try: # Añadir try/except por si ya se aplicó
             batch_op.alter_column('herramienta_id', existing_type=sa.INTEGER(), nullable=True)
         except Exception as e: print(f"Warning: could not alter herramienta_id: {e}")
         print("Batch alter analisis_resultado (handling FKs implicitly)")

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
        # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
        # batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'], ondelete='CASCADE') # COMENTADO/ELIMINADO
        # batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'], ondelete='CASCADE') # COMENTADO/ELIMINADO
        print("Batch alter analisis_similitud (handling FKs implicitly)")

    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey') # COMENTADO/ELIMINADO
        # batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'], ondelete='SET NULL') # COMENTADO/ELIMINADO
        # Si detectó el cambio a nullable=True para tipo_analisis_id, esa línea SÍ debe quedar:
        try: # Añadir try/except
            batch_op.alter_column('tipo_analisis_id', existing_type=sa.INTEGER(), nullable=True)
        except Exception as e: print(f"Warning: could not alter tipo_analisis_id: {e}")
        print("Batch alter herramienta_analisis (handling FK implicitly)")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramienta_analisis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_analisis', ['tipo_analisis_id'], ['id'])

    with op.batch_alter_table('analisis_similitud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_2'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id_1'], ['id'])

    with op.batch_alter_table('analisis_resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'herramienta_analisis', ['herramienta_id'], ['id'])
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    with op.batch_alter_table('analisis_metrica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entrega', ['entrega_id'], ['id'])

    # ### end Alembic commands ###
