"""Agregar repr a Resultado de Evaluacion

Revision ID: f92b78160074
Revises: 8a3db9111a93
Create Date: 2025-04-26 10:08:30.762490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92b78160074'
down_revision = '8a3db9111a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_de_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salida_obtenida_repr', sa.Text(), nullable=True, comment='Representación depurable (repr) de la salida obtenida'))
        batch_op.add_column(sa.Column('salida_esperada_repr', sa.Text(), nullable=True, comment='Representación depurable (repr) de la salida esperada'))
        batch_op.add_column(sa.Column('entrada_repr', sa.Text(), nullable=True, comment='Representación depurable (repr) de la entrada utilizada'))
        batch_op.add_column(sa.Column('argumentos_repr', sa.Text(), nullable=True, comment='Representación depurable (repr) de los argumentos utilizados'))
        batch_op.add_column(sa.Column('stderr_obtenido', sa.Text(), nullable=True, comment='Salida de error si existió durante la ejecución'))
        batch_op.add_column(sa.Column('stderr_obtenido_repr', sa.Text(), nullable=True, comment='Representación depurable de stderr'))
        batch_op.add_column(sa.Column('tiempo_ejecucion_ms', sa.Integer(), nullable=True, comment='Tiempo de ejecución en milisegundos'))
        batch_op.add_column(sa.Column('memoria_utilizada_kb', sa.Integer(), nullable=True, comment='Memoria utilizada en kilobytes'))
        batch_op.add_column(sa.Column('estado_ejecucion', sa.String(length=50), nullable=True, comment="Estado detallado: 'completado', 'timeout', 'error', etc."))
        batch_op.add_column(sa.Column('codigo_retorno', sa.Integer(), nullable=True, comment='Código de retorno del proceso ejecutado'))
        batch_op.add_column(sa.Column('diferencias_resumen', sa.Text(), nullable=True, comment='Resumen de diferencias entre salida esperada y obtenida'))
        batch_op.add_column(sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_de_evaluacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_ejecucion')
        batch_op.drop_column('diferencias_resumen')
        batch_op.drop_column('codigo_retorno')
        batch_op.drop_column('estado_ejecucion')
        batch_op.drop_column('memoria_utilizada_kb')
        batch_op.drop_column('tiempo_ejecucion_ms')
        batch_op.drop_column('stderr_obtenido_repr')
        batch_op.drop_column('stderr_obtenido')
        batch_op.drop_column('argumentos_repr')
        batch_op.drop_column('entrada_repr')
        batch_op.drop_column('salida_esperada_repr')
        batch_op.drop_column('salida_obtenida_repr')

    # ### end Alembic commands ###
